ALPHAPOSE:
  cfg: libraries/alphapose/configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml         # 'experiment configure file name'
  checkpoint: libraries/alphapose/pretrained_models/fast_res50_256x192.pth          # 'checkpoint file name' 
  vis: False                                                                        # 'visualize image'
  profile: False                                                                    # 'add speed profiling at screen output'
  format: coco                                                                      # 'save in the format of cmu or coco or openpose, option: coco/cmu/open'
  min_box_area: 0                                                                   # 'min box area to filter out'
  eval: False                                                                       # 'save the result json as coco format, using image index(int) instead of image name(str)'
  flip: False                                                                       # 'enable flip testing'
  vis_fast: True                                                                    # 'use fast rendering'
  pose_flow: False                                                                  # 'track humans in video with PoseFlow'
  pose_track: False                                                                 # 'track humans in video with reid'
  showbox: False                                                                    # 
